name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push 20.04
      uses: docker/build-push-action@v2
      env:
          imagetag: 20.04
      with:
          platforms: linux/amd64, linux/arm64
          context: .
          build-args: |
            TAG=${{ env.imagetag }}
          file: Dockerfile
          push: true
          tags: |
            abcdesktopio/ntlm_auth:${{ env.imagetag }}
    - name: Build and push 22.04
      uses: docker/build-push-action@v2
      env:
          imagetag: 22.04
      with:
          platforms: linux/amd64, linux/arm64
          context: .
          build-args: |
            TAG=${{ env.imagetag }}
          file: Dockerfile
          push: true
          tags: |
            abcdesktopio/ntlm_auth:${{ env.imagetag }}
